### ISSUE TITLE
Special functions for some magic methods?

### ISSUE THREAD

**Issue by ngallup** [ngallup/turboclass#13]
It may be a useful idea to create special implementations for comparative and type-like magic methods.  Some ideas:

**len** returns number of configurations

**eq** compares turboDir strings instead of instance references

**int**, **float**, return latest DFT energy in respective types.  Seems like a silly implementation for **int** though, which could maybe be better used for something else, or forgotten.

**str** returns string-type of turboDir OR string-type of latest DFT energy.  Not really sure which would be better.  Leaning towards turboDir but I don't know.

**Comment by ngallup** [comment]
**len** and **eq** have been given specific implementations

**Comment by mrnechay** [comment]
these nominated uses of "int", "float", and "str" are non-intuitive. These uses should be given descriptive names such as ".getEnergy()" and ".getDir()"

**Comment by ngallup** [comment]
We'll do that instead.  I'll close this issue.
